sprite $batman [600x337/16z] {
xDZL0QH0303Gu3ga_shFZLtax8_tEXY9njC100000000000000000000000000000000G1rFrrJnlr2r_Rpc9sqyNPjP-Zh-3LKpRbj-CqPGvsTbQkhuArJj
jELFMnsVCEGtPUcR-3FKmvexItn5jxkMeOxVH3kk-MAAxnXpRnshk4CzvRisVcBAL-KoRL6DUIHsMFBTDiGnnZnKuWKbZsn35NlKqvR7vdZ3ciTA5p_Hhdbc
Y0EKF3EtyHdrcEUQE4ALtwY7nuOjpsrL7AF9AwMpLBWGfnZocFcmBNajBZ3dZQMA1nfBteXBvAsrYOVfyvRUwYCxPvBkgWu3uTW6zrRjVxTl-cRN-a9GYSC_
lIr1JQca4wN4UYChuz_4Zp7yD6mWvwiu_qV-cCCFjbZ7MwiqTp4l6Nl8uoFhm1wV7Lu40DwQ5IRsg9yTNavi8_6lEYxwSlKYs6V6lza2zUUXBmKQ-WDRu00k
BrSl0JhgdywhZoVomN8my-Vih4CUNAvNjRKQjApuS5-Oz9OlApCQqxOHwgaFrElyNdiHvQWlv9xxCt_0QS1PN4r4tMz7i3PlzCpWthZJSnfRGgAi5uUvo61e
Xlp9bAs_MIFg1jtAaBbwek-rg9vY_Pwcpl2UjdcWmx_zF5m-Rm60fBkjSnfNGF8w1kgnpl-k-Xyq-_4Atp0S5oizzflSfFhT9zirybFF72A-mlv_FbL5kVlz
g87YTHke9zYdVz1KvUKvhZ0_FWWBNtBQfqHLBL7uVGR_yZtZQxgzuoQgHutilS6_up1m0GHt9uVcDsVddpTM81Vi0WM40aiK4tXYM8hW8eudzq3x_DVKp4RG
HmAkehkxujUp2AQhgeZ1nYUlz8WxqqfF97W6HN6UZ6rGJwHVt7Wrwv92SIoA-defsTT9Z1uX48X3yKfzJuEAvk_z0HE1N54a4gLgzx-8Zazvlh7V5HYKISVb
IE2JLlurvDXkned0_Gdu1P5npUpSJbdRd_0as6WE_8JCfjZzfyt-sepWLIGeSAVU5nImdszixoahWHp4pnYCNppXU6CLjlyBOfy44yyDh8WV4WpYQZDS3dk_
hUANJ3TxPZtBVh2DkpyDIjuez0YFl-1_C6cx-oGnhwtuES7B2QoUO3suo-wJ9nvnvN_dyNlCPzku-LOpatFb-jQluWQcTLoDpMcbSrY6_WEhuHQwjMZPJAb9
KQty1rR5JLHZ0pkdT9ndphcKKclEkUGqRJlsm7r49zLAJ_CnYFYGx7eYVLZn1rRsq34MxYMoXnM_UE_yNbl2xR275R_nlkYhQe41v9ATto2bttiCM23iASDU
3iYp-e0HYrdRybzkdDGbDNIOCTpeHZsIk1jyuWdww-cyOSLlaIxUd0u3jXG_Hpzw91EVdWXj9UNVwC2Q5NXlN_abBQj-5DZJQGVTn3v_i-RD00KrS2v8Chst
mDdeArZeFuaimc7y513HlGswUbead4a8THN_K1Z0nJhetkArdtS37ubEi_CNhGwYhvtF2vGOd91OC2zybJpw8tQmCWsQX0spqcmIrYKojWk8QGQMeHKpazX4
uNjH9J30J6A1dTNI1UwLhS2A5HumC4HjcIM52yPT4u4Lyu0Jfe7dQywgvn6-C7qj7Ebe8wdizmfmngnP7LpJPEaVpZ84tWXsUpDxPDIiq5otNuZ5erc6b7qd
BF3C6hqSATxKwjTkHC4rnQ0BqYApzvRp6KDGjC7BMaI8gVG-9vx0pRFWYwpHnnYjbfnRhNtqqTV2q_YFdVjAk1p5mJ0iCYPf_wkTwRwf77pSwCJtMK15VY6B
3uR5e1r85hiWO75b7cWMXx50D0XT0SiYUWmaWwOTM1OF3WB5ebm1pg1S0TrYnW0uWt8571OXKS0PfFc0Pb6k08lO5L0jFWO1Y-SOW6HmInDO5dTmW61mCWXq
YzmLu0nYea0nwDg1QN491mW6NJjm67JjmB88NW7UO1i4gi6i7PWMWJx06Mo3G3Ru6WI6HL0KiDW60MTmNmB81W5aO5WCsm6BY0nWyQms40oYLq0nc380Xq5x
1KoBwTMQOywrbe9it_MCp1ozrP9Jy5v-vaFAfHnjB7rww4Sh9OKGdFp0nn1pBgMDKmN3Ny_8p5fp2axESZwcUYnzEXYrvkXl-P_CjVPr-IJdTmMgHk-SNEDy
V9h5XJco3vV_AqCwnhfGhtxnnuXUTd1fw6DXLYSx-FHpwOhdswiMPIzVfpu6UfAjN3xcwPFd-dLb1x4HkzuPPerYufkrTVmrqpUh5rEfwzsW5p6LsjzViDNP
iXDxhaoz0ymiT-1pro5_4EHkV5DZQFVy_vIdKTKELd7ogOhQm4ZoqGxT3ol8ftDJDqCMx8weeWbslmY1wGIcbyl80wFg3WY2tG5e3C7sD-Dno4kZUwUrec8n
j89QO5b13T1R8UYpOCRE70jBzkEZ45vU0lDHTa5sGiX6JB70Y84u5kMAWiNv3GKBiXzJTqmv1rttOnj4r1D0H9IDaFQAQnIqLso4wB8V6-5QyrzhpQMlRStH
ZrfhBhNaSjInffvHPIVMrMWv1FbMIBcsllJbh5Q2brzmiRQvxtCGG_-a7Sd9x_by37qLlNZvYrIdzU4WhyoiwkK4b-hIfvU3d9JwXdM5jEMfiBJqUOqijmdD
P1yatNTukLcU-encaIlYsBokQDnNacj2clfa3YzN-MFZHHpMrKpo7_YgpsEclO7QBkTXzwk6QRtHwrJ7ZgiuhAiaEyIX3zUzRE7QjVD1B8DvSXZwKCERNE3r
SXfiJbLTquTfNhOg5yevhFxD_7go7V0wFsykw9Xc4P0mt-OvzNhh8tqOXYSK-MsIml76nXtTwcVy_crMSsAdtzIuOpQnvAVUInHJvPRV0LwCnNT9SxhFQzm9
qKUvWohF197ekGbqddcnWAHcffUF1JVK05Dm53N0eHs2RhUyWBtm_-tTrM73G1G4m2SmYFllDfzXlWtEj61BsjkZ_MXhhQg2EH6juFApenL2bkEeQ7yVmTxL
7T1jYSGEQ-9l1SlF-rkXRt3x4O5BdwPw1ao9lnLCYP8Thec_5LmJ7q6O4oD1M1Fx8s1BrA6m7s-trHl1yNRL7jPZTTKSTXRszGwm9GvWW2LnOXea-b3e4mq3
N1CD0wo97LsGoEmm9i8LB8bm1OcU7SR40b6O4-4A4XK3N19VGJWUsklJO4oC1M4Bh6A0Bj68mXmubnRwH6Y7EN1B5_I9pSsm1ffs61CJWx071eDm2Gm6eKiS
zmXpu90F618b0uHE-K1oh-OWiKmKbg7-9W0000000000000000000000000000000BW1
}

