sprite $bishop [76x76/16z] {
xPS7TiCu34JHs0dC_K-xHUApNlfIplRyz3R1U402flyCF_mWkMIXRo4709HlaGBWtoF6Zgaa0_6yJGECY1H8z2nf5UGetrFN-l0q3aziSvNthCcJHC-J0hyJ
cPx59W1l4y0qUWOk06OcuZG1DARRoCJbBJimXMwY3WovYko0sqsf0Chhenbwow2_pIu5_8xOk5egpSTdmAHj2Yw37UEoYRhjC33eqkhNvy1kc1NG5PzmnnJX
npzfj0K7sfNcGHWTjDrJdXvb6R1OeGgGDoqwBIobYPcIqMAYRpP4fuk6GHTriory9N_bU57WlATLw2A_KCw8FQsNmSlBBfvRMWsJFc9Wx0vhfVTHe6nFQpu_
OrKpLUP7427RMyGGjZ9yZOxmKPEGZ1kRHGF2yOhm03fjKmD0Z9gJgbhARPpIbMvGWF8oV2r0eplCTxBlcxrrPP_F84LLvSpHxkq23SuagSqLvEnPhsAtRqFh
WHVCL06ziwOUGjvAChDKsWI0kFFepqEewelTV1noiZ-748bUOuuR9XCG8xyiGQp5hMOrFzChoKpjQFoulTDnddYDLwQRQExJOybuBtQd97dCQT89uExcnKUl
nooyrYGCxK0KPMAsqbhDyeUiId4il9KwrorJ0e1FltwMlfBZ6glNpxwyrcVjE8cv5AFPPtB90OpLejPd-4XCnCQ7zzfgCI5YoStFMEKZUmr0LxfO5yt0r3SE
x92BRXzju9vU_3wnM3dDZcpAloCip2kaZiF7MwjZxQAIQf--M7T5h5bql8Jx7ENmBHM0yxjr9NfpPyKeJ5ncu1NHbAX-y0H27N4Oyj7hGIdfaPLOogNatodb
F9ke7HyD0FNhpleArjFu-AWlBB1nUALzEdWjqGwvClqR-U67Nm4
}

sprite $rook [76x76/16z] {
xTS5qg0m30NWf4ebUVU_xIw_qXbgwyA7soE3Gt-dnyEa_DO4EiMSFfhisra7qr32EpL4PD5ePo7CihISv3NB0RMy4O0lioeGPrcLJXvuox9qkfabiwpyaQKt
MNoPnR9HbzIlJPFrDcizgz39DQUWdGMpLnU7z2hGXzZCugNZDRTOrm_EuYL6vraGbPQ-jotCiWvi23J41K0AyIgyjHSX0yXC4mcebYQS0f7c8g2UXW80Joiy
WCW32H1BQwm0qgU065fb14ELDYHeFEAblVOKWJOSa7xHFp2BxxAUklXlErxcdpXUp_Lb_gBZzLnV6dkElIok62gqBWCg8dhVAf2Mgof0uZvJriCoa7csisEf
gZDgUZpNmb8JDQbiMfKuQzsmiTOlV805R72puxvk_XqjTetJl_A_mtfV8Sul2OhilQ5x1lka4-O0tGDeFyiRQrPPmn5gkrcMjdYe-N5Pw6Ub47UKKLtxEbbS
L6MZFPj4VRpN_YaUNm
}