sprite $pawn [76x76/16z] {
nPXN0kCm24GZNDHvzp_jzX9bZMAqRJvTy504Z1_l469Lq1hbyPi8cU_G57xBrDPvGjyUwzWLe9USYWBelcnAEg1d-EBigO0k1wq0BVomt82owY7GduY41Ynw
cLzVFO2yLWuTsdYfGGzBzG34yL84P3LSntZf0FR_RMi3pl7IkMfBWFnhPjSEPGKTtWmwPDQ32AJd2sd8h0idm356ddEP5kGXMel44a0_XfBe06dDmHB6Yw6i
kBafa0osllOQAf2jvb5TjewX2mweNY-RxSaEDEUnpjCMwQk7VVQXv7AnstUxnqdfqu5JF9rQW3WluytJ1Oz_OclirFxklCvBvbbFW7YcR9tsxkvQIkoD9gZh
T9-pW4NVuHQ55kn3eU9SSQ9DAxlRwcRL2-AU75sCjJFwXpPzkzohQrZOSj3NFKSzesCSXOp9Fs4OcXwreUK8m-MpA03vlfTI0JHUnJugG1ENSCbYVAW0TF6e
ZKaizQusalRsoRq3BNWAouRSAxC4wEPTNUmItU-rSOut7VLkSuflGvRkoxhonilD8JT50N6tGBkHbocjvjA4TiQJPohCfQceISic5em0cD7oZxvg9z5sf9ft
Yl-dWrYC3sSdjvmiKnTzhjZBZNlbaHK9bgv7tE4CrxXkUlzZMCwujtPxhykNOMpXuKM3vacZFv5FR1t8Lv4HXRIayFNILalPYTIkihyfYr2vuBM4IrxyFg-F
}

