sprite $king [78x76/16z] {
rLU9iYeh33I400bB_lzltmsZYDR0MALlwtDSX-bidO2tJ-1Lm-rde9-o-VOZDaz__f8gUq_UVqdcYhRMLBM_5FYIhUg4-gLlG374mAeI_ho6tzJqYohyl_H6
xR_g6w2ePlmDcMCrD7O_8CEXtuBVUzQqIpSR7NpB9ggDx4reglBzB58wtaRLzcMih9eVxxCgVpkGT0ore9hXGr45pgLa3Y_1ODCs2A2zXOhnk8VUjED51qfy
NgINcTQq-QVRgJQzeyba1LWxnbN1Pt1bPjCmjSSBqYC4BCQKEOOOETVZ8XvixxxHSSTXljez8N8nDx8RcLOP8M0GkrWZzE5n4Yd47eG4zuZDouCEx5qOgHuN
DMENMvlRejftnQuoljmIxQkUw9DnutlmuGQpGdplhM2E5Vyk5QEZlZwT22QP0n5aCfNCF9kPkD0vUDNQupzrBxtt0dV7LkC1nLmx1UP3D1MUIhQ2YrisOQeM
xYc63CFGde5XFUvB7mnxEXc1wgxl_H79agshvv5Nh7ioouHksMxG7QA71BOpnBVk75tj2ZrLvcPn-ssovekjadgezpZyRcLKvSiHc7fLUqNZTa0MLNAxK0tG
TnV8-oshcsjWjklbCkVqocZjlfjpwUfuIV7ADRahAUX58OofMzu7eFJGLCLjMGtDNsoxyWmbmpxKlTQWM9oJyNJL4B9Pm2-kftt5akxDqPiMitcwJR7Ijjtb
FJMoMRwjauoapiw6tMcah0Lqqi2MoBTO0T1JY8d5PermIe6y0xXDzL-etzKn2i4v7vBKfgUeHM90v-wS-LGyeLSPa28N_G158g6xqM9gc17EaqEjbYB2d0um
i-HSwyJOSbgL3-TLaeBtw03WDPFW42qDPRBg5XkYeN10oyaUu33muMPQYhJG6yyUG6KfQrAL1TckXVr2ygSJqNBL0N0-NjoIRMvMXnIJbR7SaRDmYeJmAjr5
E33Q0J1ogUrKlgtLmX5Xd7JSSdTgQ4pvZERjkvQZWv6SnGIDgJx5MukaQBf3XuZUXvWarpfuQueRjZo8Yd30HGZE1yvbKCfcKFK637uYif9Y_tFmGYb53Rpn
hQR111WYMqNhWM9jov7moPZQyWms7y31fxAQIAtcv648lcmKWbqUvUNkWTUI8XmINR0vrUenrU53oHo9F28wPpNrFVJXSqdeswuNsfsgPWv-PTJ7CGRhceqU
DjcwPmj0uaSCVhDjAW-TRJ5-ZYbj3zNfGpQCJNNp0y59quEGy7G03JsFG1jlR2CN7NL8aOYy0VlV7n2HzUfKrRt_Bd0zKziik56iJtBYC4gzt4pzeBe6sAJe
uwVDRjQI9MtsjBy
}

